WOOR-235/PostDetail Page API 연결
prgrms-web-devcourse/Team_02_WooriMap_FE pull request #52
Opened 2022-08-11 14:16 UTC by sangjin149

## 📌 PR 설명

#### 해당 PR은 WOOR-231 에서 만들어진 API 함수를 재사용합니다.

따라서 231번 merge 후 api 부분이 달라질 예정입니다.

- DetailPage에 단건 조회, 삭제 API 를 붙이고 페이지 이동 기능을 추가했습니다. 
- WOOR-231이 아직 머지되지 않아 Edit 버튼을 누르면 404가 나옵니다. 

### 스크린 샷

### 내용

- 단건 조회
    - CSR 로 게시물을 불러옵니다. 
    - 조회 결과 해당 게시물이 없으면 404 페이지로 이동합니다. 
- 삭제
    - 삭제 확인으로 별도의 창을 띄우기보다는 한번 text가 바뀝니다. 
    - 삭제 api 호출과 동시에 홈화면으로 이동합니다. 

## ✔️ PR 포인트 & 궁금한 점

- CSR로 하고있지만, 초기 로딩이 좀 느린데 이 부분을 개선할 수 있는지 궁금합니다. 
- 그 밖의 개선가능한 점 환영합니다!

### 🚀 연관된 이슈

WOOR-235

2022-08-11 15:48 UTC, mrbartrns requested changes
상진님 고생하셨습니다.

타입 정의 및 함수 선언 형태가 컨벤션과 많이 달라서, 해당 부분 빠르게 수정해 주시면 감사하겠습니다.

2022-08-11 15:48 UTC, mrbartrns commented on apis/post.ts
> +export const postCreate = async ({ data, instance }: IPostWriteProps) => {
컴포넌트 내부에서 사용하는 함수가 아니라면, 함수 선언형으로 함수를 구현하기로 컨벤션에 정의 했었습니다. 해당 부분 변경 바랍니다.

2022-08-11 15:48 UTC, mrbartrns commented on apis/post.ts
> +export const updatePost = async ({ instance, data, id }: IPostWriteProps) => {
여기도 마찬가지네용

2022-08-11 15:48 UTC, mrbartrns commented on apis/post.ts
> +export const getOnePost = async ({ instance, id }: IPostWriteProps) => {
여기도!

2022-08-11 15:48 UTC, mrbartrns commented on apis/post.ts
> +        },
instance hook 사용하면 token header 없어도 될 텐데, 테스트 해보시겠어요?

2022-08-11 15:48 UTC, mrbartrns commented on apis/post.ts
> +export const deletePost = async ({ instance, id }: IPostWriteProps) => {
여기도 함수 선언형으로 사용 바랍니다

2022-08-11 15:48 UTC, mrbartrns commented on components/organisms/PostBody/PostBody.tsx
> +  const handleEditClick = (e: React.MouseEvent<HTMLElement>) => {
HTMLElement는 정말 피치 못할 때를 제외하고, 구체적은 컴포넌트를 명시해 주는 것이 좋을 것 같습니다.

2022-08-11 15:48 UTC, mrbartrns commented on components/organisms/PostBody/PostBody.tsx
> +  const handleDeleteClick = (e: React.MouseEvent<HTMLElement>) => {
여기도 HTMLElement보다 구체적인 컴포넌트로 바꿔주시면 감사하겠습니다.

2022-08-11 15:48 UTC, mrbartrns commented on pages/post/[id]/index.tsx
> +  const { id } = router.query as { id: string };
ask) 해당 부분에 assertion을 사용하신 이유가 무엇인가요?

2022-08-11 15:48 UTC, mrbartrns commented on pages/post/[id]/index.tsx
> +        const res = await getOnePost({ instance, id });
줄임말은 웬만하면 사용하지 않기로 컨벤션에 정의했었습니다

res -> response

2022-08-12 01:12 UTC, sangjin149 commented on pages/post/[id]/index.tsx
> +  const { id } = router.query as { id: string };
router.query.id 값에는 string Array 가 들어갈 수 있다고 나와서, 일단 string으로 assertion을 해놨습니다!

2022-08-12 01:17 UTC, sangjin149 commented
준혁님 리뷰 반영 완료했습니다~

2022-08-12 01:22 UTC, sangjin149 commented on apis/post.ts
> +        },
interceptor를 깜빡했네요, 잘 동작합니다!

2022-08-12 06:08 UTC, MayOwall reviewed
멧 코드 작성하시느라 고생 많으셨습니다 👏👏

아래에 궁금한 것들에 대해 적어놓았으니,
한번 확인 부탁드려요! 😎

2022-08-12 06:08 UTC, MayOwall commented on apis/post.ts
>          },
인스턴스 훅을 사용하면 header는 사용하지 않아도 된다고 하네요!

테스트 해보니 저는 header없이도 잘 작동했긴 했지만,
위고 말에 의하면 header가 없을 때 오류가 나는 경우도 있다고 하더군용

한번 테스트 해 보시고 없어도 괜찮다면 header는 제외하셔도 될 것 같습니다 😉

2022-08-12 06:08 UTC, MayOwall commented on apis/post.ts
> +    })
혹시 async 내부에서 .then을 사용하신 이유가 있으실까요??
async와 .then은 섞어 사용하지 않는 것이 좋다고 알고 있어서요
제가 async await과 프로미스에 관해 잘 알지 못해 여쭤봅니다 😂

2022-08-12 06:08 UTC, MayOwall commented on components/molecules/TagInputWithList/TagInputWithList.tsx
> +    getAllTags();
메인페이지에서 사용하는 전체 태그리스트 get과 같은 용도의 로직이니,
나중에 기회가 된다면 함께 합쳐보아요~

2022-08-12 06:16 UTC, Yummy-sk approved these changes

2022-08-12 06:30 UTC, sangjin149 commented on apis/post.ts
> +    })
아 그런가요?? 저도 좀 알아보고 답변 드리겠습니다.

2022-08-12 11:46 UTC, merged